### PR TITLE
germans translation hopefully?

### PR DESCRIPTION
**Pull request by MojoJMP**
sorry idk how github works i am overwhelmed

### CODE REVIEW

**Comment by Moffein** [comment]
Thanks. I'll release an update shortly.

**Comment by Moffein** [comment]
If you're still around, would you be able to update the German translation?
I'm updating Steady Aim to have Weak Point support like Railgunner, and the skill's description needs to be rewritten.

**Comment by MojoJMP** [comment]
yea sure i can do that

**Comment by Moffein** [comment]
Alright, need translations for:
SNIPERCLASSIC_SECONDARY_DESCRIPTION
KEYWORD_SNIPERCLASSIC_WEAKPOINT
KEYWORD_SNIPERCLASSIC_OVERCHARGE

Secondary was changed, which was why it needs to be re-translated. Secondary/Weakpoint strings are based on Railgunner's.

**Comment by Moffein** [comment]
Nevermind, descriptions have been updated.

**Comment by MojoJMP** [comment]
my bad, didnt see that last part

**Pull request merged**
